"""Phase 4: Password Reset, Account Page, Admin Panel"""
from pathlib import Path

ROOT    = Path(__file__).parent
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"

# ── email_handler.py ──────────────────────────────────────────────────────────
(BACKEND / "email_handler.py").write_text(
    'import smtplib, os\n'
    'from email.mime.text import MIMEText\n\n\n'
    'def send_reset_email(to_email: str, reset_url: str) -> bool:\n'
    '    host  = os.environ.get("SMTP_HOST", "")\n'
    '    port  = int(os.environ.get("SMTP_PORT", "587"))\n'
    '    user  = os.environ.get("SMTP_USER", "")\n'
    '    pw    = os.environ.get("SMTP_PASS", "")\n'
    '    frm   = os.environ.get("SMTP_FROM", user)\n'
    '    if not host or not user:\n'
    '        print(f"[RESET LINK] {to_email} -> {reset_url}")\n'
    '        return True\n'
    '    msg = MIMEText(\n'
    '        f"Hallo,\\n\\nPasswort zuruecksetzen:\\n\\n{reset_url}\\n\\n"\n'
    '        "Der Link ist 1 Stunde gueltig.\\n\\nRS Platform"\n'
    '    )\n'
    '    msg["Subject"] = "RS Platform - Passwort zuruecksetzen"\n'
    '    msg["From"]    = frm\n'
    '    msg["To"]      = to_email\n'
    '    try:\n'
    '        with smtplib.SMTP(host, port) as s:\n'
    '            s.starttls()\n'
    '            s.login(user, pw)\n'
    '            s.send_message(msg)\n'
    '        return True\n'
    '    except Exception as e:\n'
    '        print(f"[EMAIL ERROR] {e}")\n'
    '        print(f"[RESET LINK] {to_email} -> {reset_url}")\n'
    '        return False\n',
    encoding="utf-8",
)
print("wrote backend/email_handler.py")

# ── auth.py ───────────────────────────────────────────────────────────────────
(BACKEND / "auth.py").write_text(
    'from datetime import datetime, timedelta\n'
    'from pathlib import Path\n'
    'import os, sqlite3, secrets\n\n'
    'import bcrypt as _bcrypt\n'
    'from jose import JWTError, jwt\n\n'
    'SECRET_KEY          = os.environ.get("SECRET_KEY", "CHANGE-ME-use-openssl-rand-hex-32")\n'
    'ALGORITHM           = "HS256"\n'
    'TOKEN_EXPIRE_HOURS  = 24 * 7\n'
    'RESET_EXPIRE_HOURS  = 1\n\n'
    'DB_PATH = Path(__file__).parent / "users.db"\n\n\n'
    'def init_db() -> None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute("""\n'
    '            CREATE TABLE IF NOT EXISTS users (\n'
    '                id                INTEGER PRIMARY KEY AUTOINCREMENT,\n'
    '                email             TEXT    UNIQUE NOT NULL,\n'
    '                password_hash     TEXT    NOT NULL,\n'
    '                plan              TEXT    DEFAULT \'free\',\n'
    '                stripe_customer_id TEXT,\n'
    '                is_active         INTEGER DEFAULT 1,\n'
    '                is_admin          INTEGER DEFAULT 0,\n'
    '                reset_token       TEXT,\n'
    '                reset_token_exp   TEXT,\n'
    '                created_at        TEXT    DEFAULT CURRENT_TIMESTAMP\n'
    '            )\n'
    '        """)\n'
    '        cols = {r[1] for r in conn.execute("PRAGMA table_info(users)")}\n'
    '        for col, defn in [\n'
    '            ("plan",               "TEXT DEFAULT \'free\'"),\n'
    '            ("stripe_customer_id", "TEXT"),\n'
    '            ("is_admin",           "INTEGER DEFAULT 0"),\n'
    '            ("reset_token",        "TEXT"),\n'
    '            ("reset_token_exp",    "TEXT"),\n'
    '        ]:\n'
    '            if col not in cols:\n'
    '                conn.execute(f"ALTER TABLE users ADD COLUMN {col} {defn}")\n\n\n'
    'def get_user(email: str) -> dict | None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.row_factory = sqlite3.Row\n'
    '        row = conn.execute(\n'
    '            "SELECT * FROM users WHERE email = ? AND is_active = 1", (email,)\n'
    '        ).fetchone()\n'
    '    return dict(row) if row else None\n\n\n'
    'def get_all_users() -> list[dict]:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.row_factory = sqlite3.Row\n'
    '        rows = conn.execute(\n'
    '            "SELECT id, email, plan, is_active, is_admin, created_at FROM users ORDER BY id"\n'
    '        ).fetchall()\n'
    '    return [dict(r) for r in rows]\n\n\n'
    'def create_user(email: str, password: str, is_admin: int = 0) -> None:\n'
    '    hashed = _bcrypt.hashpw(password.encode("utf-8")[:72], _bcrypt.gensalt()).decode()\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute(\n'
    '            "INSERT INTO users (email, password_hash, is_admin) VALUES (?, ?, ?)",\n'
    '            (email, hashed, is_admin),\n'
    '        )\n\n\n'
    'def get_user_plan(email: str) -> str:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        row = conn.execute(\n'
    '            "SELECT plan FROM users WHERE email = ? AND is_active = 1", (email,)\n'
    '        ).fetchone()\n'
    '    return (row[0] if row else None) or "free"\n\n\n'
    'def set_user_plan(email: str, plan: str, customer_id: str | None = None) -> None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        if customer_id:\n'
    '            conn.execute(\n'
    '                "UPDATE users SET plan=?, stripe_customer_id=? WHERE email=?",\n'
    '                (plan, customer_id, email),\n'
    '            )\n'
    '        else:\n'
    '            conn.execute("UPDATE users SET plan=? WHERE email=?", (plan, email))\n\n\n'
    'def downgrade_by_customer(customer_id: str) -> None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute(\n'
    '            "UPDATE users SET plan=\'free\' WHERE stripe_customer_id=?",\n'
    '            (customer_id,),\n'
    '        )\n\n\n'
    'def check_is_admin(email: str) -> bool:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        row = conn.execute(\n'
    '            "SELECT is_admin FROM users WHERE email=? AND is_active=1", (email,)\n'
    '        ).fetchone()\n'
    '    return bool(row and row[0])\n\n\n'
    'def set_admin(email: str, is_admin: bool) -> None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute("UPDATE users SET is_admin=? WHERE email=?", (int(is_admin), email))\n\n\n'
    'def set_active(email: str, is_active: bool) -> None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute("UPDATE users SET is_active=? WHERE email=?", (int(is_active), email))\n\n\n'
    'def change_password(email: str, new_password: str) -> None:\n'
    '    hashed = _bcrypt.hashpw(new_password.encode("utf-8")[:72], _bcrypt.gensalt()).decode()\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute("UPDATE users SET password_hash=? WHERE email=?", (hashed, email))\n\n\n'
    'def create_reset_token(email: str) -> str | None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        row = conn.execute(\n'
    '            "SELECT id FROM users WHERE email=? AND is_active=1", (email,)\n'
    '        ).fetchone()\n'
    '        if not row:\n'
    '            return None\n'
    '        token   = secrets.token_urlsafe(32)\n'
    '        expires = (datetime.utcnow() + timedelta(hours=RESET_EXPIRE_HOURS)).isoformat()\n'
    '        conn.execute(\n'
    '            "UPDATE users SET reset_token=?, reset_token_exp=? WHERE email=?",\n'
    '            (token, expires, email),\n'
    '        )\n'
    '    return token\n\n\n'
    'def validate_reset_token(token: str) -> str | None:\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        row = conn.execute(\n'
    '            "SELECT email, reset_token_exp FROM users WHERE reset_token=? AND is_active=1",\n'
    '            (token,),\n'
    '        ).fetchone()\n'
    '    if not row:\n'
    '        return None\n'
    '    if datetime.utcnow().isoformat() > row[1]:\n'
    '        return None\n'
    '    return row[0]\n\n\n'
    'def use_reset_token(token: str, new_password: str) -> bool:\n'
    '    email = validate_reset_token(token)\n'
    '    if not email:\n'
    '        return False\n'
    '    hashed = _bcrypt.hashpw(new_password.encode("utf-8")[:72], _bcrypt.gensalt()).decode()\n'
    '    with sqlite3.connect(DB_PATH) as conn:\n'
    '        conn.execute(\n'
    '            "UPDATE users SET password_hash=?, reset_token=NULL, reset_token_exp=NULL WHERE email=?",\n'
    '            (hashed, email),\n'
    '        )\n'
    '    return True\n\n\n'
    'def verify_password(plain: str, hashed: str) -> bool:\n'
    '    return _bcrypt.checkpw(plain.encode("utf-8")[:72], hashed.encode("utf-8"))\n\n\n'
    'def create_token(email: str) -> str:\n'
    '    expire = datetime.utcnow() + timedelta(hours=TOKEN_EXPIRE_HOURS)\n'
    '    return jwt.encode({"sub": email, "exp": expire}, SECRET_KEY, algorithm=ALGORITHM)\n\n\n'
    'def decode_token(token: str) -> str | None:\n'
    '    try:\n'
    '        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])\n'
    '        return payload.get("sub")\n'
    '    except JWTError:\n'
    '        return None\n',
    encoding="utf-8",
)
print("wrote backend/auth.py")

# ── set_admin.py ──────────────────────────────────────────────────────────────
(BACKEND / "set_admin.py").write_text(
    '"""Admin setzen. Aufruf: python set_admin.py email@example.com"""\n'
    'import sys\n'
    'from auth import init_db, set_admin, get_user\n\n'
    'if len(sys.argv) != 2:\n'
    '    print("Verwendung: python set_admin.py <email>")\n'
    '    sys.exit(1)\n\n'
    'email = sys.argv[1]\n'
    'init_db()\n'
    'if not get_user(email):\n'
    '    print(f"User \'{email}\' nicht gefunden.")\n'
    '    sys.exit(1)\n'
    'set_admin(email, True)\n'
    'print(f"User \'{email}\' ist jetzt Admin.")\n',
    encoding="utf-8",
)
print("wrote backend/set_admin.py")

# ── main.py ───────────────────────────────────────────────────────────────────
(BACKEND / "main.py").write_text(
    'from fastapi import FastAPI, HTTPException, Depends, Request, BackgroundTasks\n'
    'from fastapi.middleware.cors import CORSMiddleware\n'
    'from fastapi.staticfiles import StaticFiles\n'
    'from fastapi.responses import JSONResponse\n'
    'from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials\n'
    'from pydantic import BaseModel\n'
    'import json, os, re\n'
    'from pathlib import Path\n\n'
    'from dotenv import load_dotenv\n'
    'load_dotenv(Path(__file__).parent.parent / ".env")\n\n'
    'from auth import (\n'
    '    init_db, get_user, verify_password, create_token, decode_token,\n'
    '    get_user_plan, set_user_plan, downgrade_by_customer,\n'
    '    check_is_admin, set_admin, set_active, change_password,\n'
    '    create_reset_token, use_reset_token, get_all_users, create_user,\n'
    ')\n'
    'from stripe_handler import create_checkout_session, parse_webhook\n'
    'from email_handler import send_reset_email\n\n'
    'app = FastAPI(title="RS Platform")\n\n'
    'app.add_middleware(\n'
    '    CORSMiddleware,\n'
    '    allow_origins=["*"],\n'
    '    allow_methods=["GET", "POST", "PATCH", "DELETE"],\n'
    '    allow_headers=["*"],\n'
    ')\n\n'
    'DATA_DIR     = Path(r"C:\\Users\\danie\\Rel.-Strength")\n'
    'MARKET_FILES = {"nasdaq": "rs_full.json", "sp500": "rs_sp500.json", "dax": "rs_dax.json"}\n'
    'PRO_MARKETS  = {"sp500", "dax"}\n'
    'FREE_LIMIT   = 20\n'
    'security     = HTTPBearer()\n\n\n'
    'def _load(path: Path):\n'
    '    with open(path, encoding="utf-8") as f:\n'
    '        return json.load(f)\n\n\n'
    'def require_auth(credentials: HTTPAuthorizationCredentials = Depends(security)) -> str:\n'
    '    email = decode_token(credentials.credentials)\n'
    '    if not email:\n'
    '        raise HTTPException(401, "Token ungueltig oder abgelaufen")\n'
    '    return email\n\n\n'
    'def require_admin(email: str = Depends(require_auth)) -> str:\n'
    '    if not check_is_admin(email):\n'
    '        raise HTTPException(403, "Kein Admin-Zugriff")\n'
    '    return email\n\n\n'
    'class LoginRequest(BaseModel):\n'
    '    email: str\n'
    '    password: str\n\n'
    'class ForgotRequest(BaseModel):\n'
    '    email: str\n\n'
    'class ResetRequest(BaseModel):\n'
    '    token: str\n'
    '    password: str\n\n'
    'class ChangePasswordRequest(BaseModel):\n'
    '    current_password: str\n'
    '    new_password: str\n\n'
    'class AdminCreateUser(BaseModel):\n'
    '    email: str\n'
    '    password: str\n'
    '    plan: str = "free"\n'
    '    is_admin: bool = False\n\n'
    'class AdminPatchUser(BaseModel):\n'
    '    plan: str | None = None\n'
    '    is_admin: bool | None = None\n'
    '    is_active: bool | None = None\n'
    '    new_password: str | None = None\n\n\n'
    '@app.on_event("startup")\n'
    'async def startup():\n'
    '    init_db()\n\n\n'
    '@app.post("/api/auth/login")\n'
    'async def login(req: LoginRequest):\n'
    '    user = get_user(req.email)\n'
    '    if not user or not verify_password(req.password, user["password_hash"]):\n'
    '        raise HTTPException(401, "E-Mail oder Passwort falsch")\n'
    '    return {"token": create_token(req.email), "email": req.email}\n\n\n'
    '@app.post("/api/auth/forgot")\n'
    'async def forgot(req: ForgotRequest, bg: BackgroundTasks):\n'
    '    token = create_reset_token(req.email)\n'
    '    if token:\n'
    '        app_url = os.environ.get("APP_URL", "http://localhost:8000")\n'
    '        url = f"{app_url}/reset.html?token={token}"\n'
    '        bg.add_task(send_reset_email, req.email, url)\n'
    '    return {"detail": "Wenn deine E-Mail registriert ist, wurde ein Reset-Link versandt."}\n\n\n'
    '@app.post("/api/auth/reset")\n'
    'async def reset_password(req: ResetRequest):\n'
    '    if len(req.password) < 8:\n'
    '        raise HTTPException(400, "Passwort muss mindestens 8 Zeichen lang sein")\n'
    '    if not use_reset_token(req.token, req.password):\n'
    '        raise HTTPException(400, "Token ungueltig oder abgelaufen")\n'
    '    return {"detail": "Passwort erfolgreich geaendert"}\n\n\n'
    '@app.get("/api/user/me")\n'
    'async def me(email: str = Depends(require_auth)):\n'
    '    return {"email": email, "plan": get_user_plan(email), "is_admin": check_is_admin(email)}\n\n\n'
    '@app.post("/api/user/change-password")\n'
    'async def user_change_password(req: ChangePasswordRequest, email: str = Depends(require_auth)):\n'
    '    user = get_user(email)\n'
    '    if not user or not verify_password(req.current_password, user["password_hash"]):\n'
    '        raise HTTPException(401, "Aktuelles Passwort falsch")\n'
    '    if len(req.new_password) < 8:\n'
    '        raise HTTPException(400, "Neues Passwort muss mindestens 8 Zeichen lang sein")\n'
    '    change_password(email, req.new_password)\n'
    '    return {"detail": "Passwort geaendert"}\n\n\n'
    '@app.get("/api/admin/users")\n'
    'async def admin_list_users(_: str = Depends(require_admin)):\n'
    '    return get_all_users()\n\n\n'
    '@app.post("/api/admin/users")\n'
    'async def admin_create_user(req: AdminCreateUser, _: str = Depends(require_admin)):\n'
    '    if get_user(req.email):\n'
    '        raise HTTPException(409, "E-Mail bereits vergeben")\n'
    '    if len(req.password) < 8:\n'
    '        raise HTTPException(400, "Passwort muss mindestens 8 Zeichen lang sein")\n'
    '    create_user(req.email, req.password, int(req.is_admin))\n'
    '    if req.plan != "free":\n'
    '        set_user_plan(req.email, req.plan)\n'
    '    return {"detail": f"User {req.email!r} angelegt"}\n\n\n'
    '@app.patch("/api/admin/users/{target}")\n'
    'async def admin_patch_user(target: str, req: AdminPatchUser, admin: str = Depends(require_admin)):\n'
    '    if req.plan is not None:\n'
    '        set_user_plan(target, req.plan)\n'
    '    if req.is_admin is not None:\n'
    '        if target == admin and not req.is_admin:\n'
    '            raise HTTPException(400, "Du kannst dir selbst nicht die Admin-Rechte entziehen")\n'
    '        set_admin(target, req.is_admin)\n'
    '    if req.is_active is not None:\n'
    '        set_active(target, req.is_active)\n'
    '    if req.new_password:\n'
    '        if len(req.new_password) < 8:\n'
    '            raise HTTPException(400, "Passwort muss mindestens 8 Zeichen lang sein")\n'
    '        change_password(target, req.new_password)\n'
    '    return {"detail": "Gespeichert"}\n\n\n'
    '@app.get("/api/rs/{market}")\n'
    'async def get_rs(market: str, email: str = Depends(require_auth)):\n'
    '    if market not in MARKET_FILES:\n'
    '        raise HTTPException(404, f"Unbekannter Markt \'{market}\'")\n'
    '    plan = get_user_plan(email)\n'
    '    if market in PRO_MARKETS and plan != "pro":\n'
    '        raise HTTPException(403, "DAX und S&P500 erfordern ein Pro-Abo")\n'
    '    path = DATA_DIR / MARKET_FILES[market]\n'
    '    if not path.exists():\n'
    '        raise HTTPException(503, "Datendatei noch nicht vorhanden")\n'
    '    data = _load(path)\n'
    '    if plan == "free" and isinstance(data, dict) and "data" in data:\n'
    '        data = {**data, "data": data["data"][:FREE_LIMIT]}\n'
    '    return JSONResponse(content=data)\n\n\n'
    '@app.get("/api/backtest/{ticker}")\n'
    'async def get_backtest(ticker: str, email: str = Depends(require_auth)):\n'
    '    if get_user_plan(email) != "pro":\n'
    '        raise HTTPException(403, "Backtests erfordern ein Pro-Abo")\n'
    '    safe = re.sub(r"[^a-z0-9]", "_", ticker.lower())\n'
    '    path = DATA_DIR / f"backtest_{safe}.json"\n'
    '    if not path.exists():\n'
    '        raise HTTPException(404, f"Keine Backtest-Daten fuer \'{ticker}\'")\n'
    '    return JSONResponse(content=_load(path))\n\n\n'
    '@app.get("/api/signals")\n'
    'async def get_signals(email: str = Depends(require_auth)):\n'
    '    if get_user_plan(email) != "pro":\n'
    '        raise HTTPException(403, "Signals erfordern ein Pro-Abo")\n'
    '    path = DATA_DIR / "signals.json"\n'
    '    if not path.exists():\n'
    '        return JSONResponse(content={})\n'
    '    return JSONResponse(content=_load(path))\n\n\n'
    '@app.get("/api/ratings")\n'
    'async def get_ratings(email: str = Depends(require_auth)):\n'
    '    path = DATA_DIR / "ratings" / "index.json"\n'
    '    if not path.exists():\n'
    '        return JSONResponse(content={"ratings": []})\n'
    '    return JSONResponse(content=_load(path))\n\n\n'
    '@app.get("/api/stripe/checkout")\n'
    'async def checkout(email: str = Depends(require_auth)):\n'
    '    return {"url": create_checkout_session(email)}\n\n\n'
    '@app.post("/api/stripe/webhook")\n'
    'async def webhook(request: Request):\n'
    '    payload = await request.body()\n'
    '    sig = request.headers.get("stripe-signature", "")\n'
    '    try:\n'
    '        event = parse_webhook(payload, sig)\n'
    '    except Exception as e:\n'
    '        raise HTTPException(400, str(e))\n'
    '    t = event["type"]\n'
    '    if t == "checkout.session.completed":\n'
    '        obj = event["data"]["object"]\n'
    '        set_user_plan(obj["customer_email"], "pro", obj.get("customer"))\n'
    '    elif t in ("customer.subscription.deleted", "customer.subscription.paused"):\n'
    '        cid = event["data"]["object"].get("customer")\n'
    '        if cid:\n'
    '            downgrade_by_customer(cid)\n'
    '    return {"ok": True}\n\n\n'
    '@app.get("/health")\n'
    'async def health():\n'
    '    return {"status": "ok", "data_dir_exists": DATA_DIR.exists()}\n\n\n'
    '_frontend = Path(__file__).parent.parent / "frontend"\n'
    'if _frontend.exists():\n'
    '    app.mount("/", StaticFiles(directory=str(_frontend), html=True), name="static")\n',
    encoding="utf-8",
)
print("wrote backend/main.py")

# ── forgot.html ───────────────────────────────────────────────────────────────
(FRONTEND / "forgot.html").write_text(
    '<!DOCTYPE html>\n<html lang="de">\n<head>\n'
    '  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
    '  <title>RS Platform - Passwort vergessen</title>\n'
    '  <style>\n'
    '    * { box-sizing: border-box; margin: 0; padding: 0; }\n'
    '    body { background: #0a0f1e; color: #e2e8f0; font-family: \'Inter\', system-ui, sans-serif;\n'
    '           min-height: 100vh; display: flex; align-items: center; justify-content: center; }\n'
    '    .card { background: #0f172a; border: 1px solid #1e293b; border-radius: 12px; padding: 40px; width: 100%; max-width: 380px; }\n'
    '    h1 { font-size: 20px; font-weight: 600; margin-bottom: 6px; color: #f1f5f9; }\n'
    '    .sub { font-size: 13px; color: #64748b; margin-bottom: 32px; }\n'
    '    label { display: block; font-size: 11px; color: #94a3b8; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 0.06em; }\n'
    '    input { width: 100%; background: #1e293b; border: 1px solid #334155; border-radius: 6px; color: #e2e8f0; font-size: 14px; padding: 10px 14px; margin-bottom: 18px; outline: none; transition: border-color 0.15s; }\n'
    '    input:focus { border-color: #3b82f6; }\n'
    '    button { width: 100%; background: #2563eb; border: none; border-radius: 6px; color: #fff; font-size: 14px; font-weight: 500; padding: 11px; cursor: pointer; }\n'
    '    button:hover:not(:disabled) { background: #1d4ed8; }\n'
    '    button:disabled { background: #1e3a5f; cursor: not-allowed; color: #64748b; }\n'
    '    .msg { border-radius: 6px; font-size: 13px; padding: 10px 14px; margin-bottom: 16px; display: none; }\n'
    '    .err { background: #450a0a; border: 1px solid #7f1d1d; color: #fca5a5; }\n'
    '    .ok  { background: #052e16; border: 1px solid #166534; color: #86efac; }\n'
    '    .back { display: block; text-align: center; margin-top: 20px; font-size: 13px; color: #64748b; text-decoration: none; }\n'
    '    .back:hover { color: #94a3b8; }\n'
    '  </style>\n</head>\n<body>\n'
    '  <div class="card">\n'
    '    <h1>Passwort vergessen</h1>\n'
    '    <p class="sub">Wir senden dir einen Reset-Link.</p>\n'
    '    <div class="msg err" id="err"></div>\n'
    '    <div class="msg ok"  id="ok"></div>\n'
    '    <form id="form">\n'
    '      <label>E-Mail</label>\n'
    '      <input type="email" id="email" required placeholder="name@example.com">\n'
    '      <button type="submit" id="btn">Link anfordern</button>\n'
    '    </form>\n'
    '    <a class="back" href="/login.html">Zurueck zum Login</a>\n'
    '  </div>\n'
    '  <script>\n'
    '    document.getElementById("form").addEventListener("submit", async function(e) {\n'
    '      e.preventDefault();\n'
    '      var btn=document.getElementById("btn"), err=document.getElementById("err"), ok=document.getElementById("ok");\n'
    '      btn.disabled=true; btn.textContent="Senden..."; err.style.display="none"; ok.style.display="none";\n'
    '      try {\n'
    '        var r = await fetch("/api/auth/forgot", { method:"POST", headers:{"Content-Type":"application/json"},\n'
    '          body: JSON.stringify({email: document.getElementById("email").value}) });\n'
    '        var d = await r.json();\n'
    '        if (!r.ok) throw new Error(d.detail||"Fehler");\n'
    '        ok.textContent=d.detail; ok.style.display="block";\n'
    '        document.getElementById("form").style.display="none";\n'
    '      } catch(ex) {\n'
    '        err.textContent=ex.message; err.style.display="block";\n'
    '        btn.disabled=false; btn.textContent="Link anfordern";\n'
    '      }\n'
    '    });\n'
    '  </script>\n</body>\n</html>\n',
    encoding="utf-8",
)
print("wrote frontend/forgot.html")

# ── reset.html ────────────────────────────────────────────────────────────────
(FRONTEND / "reset.html").write_text(
    '<!DOCTYPE html>\n<html lang="de">\n<head>\n'
    '  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
    '  <title>RS Platform - Neues Passwort</title>\n'
    '  <style>\n'
    '    * { box-sizing: border-box; margin: 0; padding: 0; }\n'
    '    body { background: #0a0f1e; color: #e2e8f0; font-family: \'Inter\', system-ui, sans-serif;\n'
    '           min-height: 100vh; display: flex; align-items: center; justify-content: center; }\n'
    '    .card { background: #0f172a; border: 1px solid #1e293b; border-radius: 12px; padding: 40px; width: 100%; max-width: 380px; }\n'
    '    h1 { font-size: 20px; font-weight: 600; margin-bottom: 6px; color: #f1f5f9; }\n'
    '    .sub { font-size: 13px; color: #64748b; margin-bottom: 32px; }\n'
    '    label { display: block; font-size: 11px; color: #94a3b8; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 0.06em; }\n'
    '    input { width: 100%; background: #1e293b; border: 1px solid #334155; border-radius: 6px; color: #e2e8f0; font-size: 14px; padding: 10px 14px; margin-bottom: 18px; outline: none; transition: border-color 0.15s; }\n'
    '    input:focus { border-color: #3b82f6; }\n'
    '    button { width: 100%; background: #2563eb; border: none; border-radius: 6px; color: #fff; font-size: 14px; font-weight: 500; padding: 11px; cursor: pointer; }\n'
    '    button:hover:not(:disabled) { background: #1d4ed8; }\n'
    '    button:disabled { background: #1e3a5f; cursor: not-allowed; color: #64748b; }\n'
    '    .msg { border-radius: 6px; font-size: 13px; padding: 10px 14px; margin-bottom: 16px; display: none; }\n'
    '    .err { background: #450a0a; border: 1px solid #7f1d1d; color: #fca5a5; }\n'
    '    .ok  { background: #052e16; border: 1px solid #166534; color: #86efac; }\n'
    '  </style>\n</head>\n<body>\n'
    '  <div class="card">\n'
    '    <h1>Neues Passwort</h1>\n'
    '    <p class="sub">Mindestens 8 Zeichen.</p>\n'
    '    <div class="msg err" id="err"></div>\n'
    '    <div class="msg ok"  id="ok"></div>\n'
    '    <form id="form">\n'
    '      <label>Neues Passwort</label>\n'
    '      <input type="password" id="pw1" required placeholder="........">\n'
    '      <label>Wiederholen</label>\n'
    '      <input type="password" id="pw2" required placeholder="........">\n'
    '      <button type="submit" id="btn">Passwort speichern</button>\n'
    '    </form>\n'
    '  </div>\n'
    '  <script>\n'
    '    var token = new URLSearchParams(location.search).get("token");\n'
    '    if (!token) {\n'
    '      document.getElementById("err").textContent = "Kein gueltiger Reset-Link.";\n'
    '      document.getElementById("err").style.display = "block";\n'
    '      document.getElementById("form").style.display = "none";\n'
    '    }\n'
    '    document.getElementById("form").addEventListener("submit", async function(e) {\n'
    '      e.preventDefault();\n'
    '      var btn=document.getElementById("btn"), err=document.getElementById("err"), ok=document.getElementById("ok");\n'
    '      var pw1=document.getElementById("pw1").value, pw2=document.getElementById("pw2").value;\n'
    '      err.style.display="none"; ok.style.display="none";\n'
    '      if (pw1!==pw2) { err.textContent="Passwoerter stimmen nicht ueberein."; err.style.display="block"; return; }\n'
    '      btn.disabled=true; btn.textContent="Speichern...";\n'
    '      try {\n'
    '        var r = await fetch("/api/auth/reset", { method:"POST", headers:{"Content-Type":"application/json"},\n'
    '          body: JSON.stringify({token: token, password: pw1}) });\n'
    '        var d = await r.json();\n'
    '        if (!r.ok) throw new Error(d.detail||"Fehler");\n'
    '        ok.textContent="Passwort geaendert. Weiterleitung..."; ok.style.display="block";\n'
    '        document.getElementById("form").style.display="none";\n'
    '        setTimeout(function(){ window.location.href="/login.html"; }, 2000);\n'
    '      } catch(ex) {\n'
    '        err.textContent=ex.message; err.style.display="block";\n'
    '        btn.disabled=false; btn.textContent="Passwort speichern";\n'
    '      }\n'
    '    });\n'
    '  </script>\n</body>\n</html>\n',
    encoding="utf-8",
)
print("wrote frontend/reset.html")

# ── account.html ──────────────────────────────────────────────────────────────
(FRONTEND / "account.html").write_text(
    '<!DOCTYPE html>\n<html lang="de">\n<head>\n'
    '  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
    '  <title>RS Platform - Konto</title>\n'
    '  <style>\n'
    '    * { box-sizing: border-box; margin: 0; padding: 0; }\n'
    '    body { background: #0a0f1e; color: #e2e8f0; font-family: \'Inter\', system-ui, sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; }\n'
    '    .card { background: #0f172a; border: 1px solid #1e293b; border-radius: 12px; padding: 40px; width: 100%; max-width: 420px; }\n'
    '    h1 { font-size: 20px; font-weight: 600; margin-bottom: 28px; color: #f1f5f9; }\n'
    '    .row { display: flex; justify-content: space-between; align-items: center; padding: 12px 0; border-bottom: 1px solid #1e293b; font-size: 14px; }\n'
    '    .lbl { color: #64748b; } .val { color: #f1f5f9; font-weight: 500; }\n'
    '    .badge { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }\n'
    '    .pro  { background: #1e3a5f; color: #60a5fa; }\n'
    '    .free { background: #1e293b; color: #94a3b8; }\n'
    '    h2 { font-size: 14px; font-weight: 600; color: #64748b; margin: 28px 0 16px; text-transform: uppercase; letter-spacing: 0.06em; }\n'
    '    label { display: block; font-size: 11px; color: #94a3b8; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 0.06em; }\n'
    '    input { width: 100%; background: #1e293b; border: 1px solid #334155; border-radius: 6px; color: #e2e8f0; font-size: 14px; padding: 10px 14px; margin-bottom: 14px; outline: none; transition: border-color 0.15s; }\n'
    '    input:focus { border-color: #3b82f6; }\n'
    '    button { width: 100%; background: #2563eb; border: none; border-radius: 6px; color: #fff; font-size: 14px; font-weight: 500; padding: 11px; cursor: pointer; transition: background 0.15s; }\n'
    '    button:hover:not(:disabled) { background: #1d4ed8; }\n'
    '    button:disabled { background: #1e3a5f; cursor: not-allowed; color: #64748b; }\n'
    '    .btn-muted { background: #1e293b; color: #94a3b8; margin-top: 10px; }\n'
    '    .btn-muted:hover { background: #334155; }\n'
    '    .msg { border-radius: 6px; font-size: 13px; padding: 10px 14px; margin-bottom: 14px; display: none; }\n'
    '    .err { background: #450a0a; border: 1px solid #7f1d1d; color: #fca5a5; }\n'
    '    .ok  { background: #052e16; border: 1px solid #166534; color: #86efac; }\n'
    '    .nav { font-size: 13px; margin-bottom: 24px; display: flex; gap: 16px; }\n'
    '    .nav a { color: #64748b; text-decoration: none; } .nav a:hover { color: #94a3b8; }\n'
    '    .upgrade-btn { background: #2563eb; color: #fff; border: none; padding: 3px 12px; border-radius: 4px; font-size: 12px; cursor: pointer; }\n'
    '  </style>\n</head>\n<body>\n'
    '  <div class="card">\n'
    '    <div class="nav"><a href="/">Dashboard</a><span id="adm" style="display:none"><a href="/admin.html">Admin</a></span></div>\n'
    '    <h1>Mein Konto</h1>\n'
    '    <div class="row"><span class="lbl">E-Mail</span><span class="val" id="em"></span></div>\n'
    '    <div class="row"><span class="lbl">Plan</span><span class="val" id="pl"></span></div>\n'
    '    <h2>Passwort aendern</h2>\n'
    '    <div class="msg err" id="err"></div>\n'
    '    <div class="msg ok"  id="ok"></div>\n'
    '    <form id="form">\n'
    '      <label>Aktuelles Passwort</label><input type="password" id="cur" required placeholder="........">\n'
    '      <label>Neues Passwort</label><input type="password" id="nw" required placeholder="........">\n'
    '      <label>Wiederholen</label><input type="password" id="nw2" required placeholder="........">\n'
    '      <button type="submit" id="btn">Passwort aendern</button>\n'
    '    </form>\n'
    '    <button class="btn-muted" onclick="localStorage.clear();window.location.href=\'/login.html\'">Abmelden</button>\n'
    '  </div>\n'
    '  <script>\n'
    '    var _t=localStorage.getItem("rs_token"); if(!_t) window.location.href="/login.html";\n'
    '    function api(url,o){o=o||{};o.headers=Object.assign({},o.headers,{"Authorization":"Bearer "+_t});return fetch(url,o).then(function(r){if(r.status===401){localStorage.clear();window.location.href="/login.html";}return r;});}\n'
    '    async function load(){\n'
    '      var r=await api("/api/user/me"), u=await r.json();\n'
    '      document.getElementById("em").textContent=u.email;\n'
    '      var pl=document.getElementById("pl");\n'
    '      if(u.plan==="pro") pl.innerHTML=\'<span class="badge pro">Pro</span>\';\n'
    '      else pl.innerHTML=\'<span class="badge free">Free</span> <button class="upgrade-btn" onclick="upgrade()">Upgrade</button>\';\n'
    '      if(u.is_admin) document.getElementById("adm").style.display="";\n'
    '    }\n'
    '    async function upgrade(){var r=await api("/api/stripe/checkout");var d=await r.json();if(d.url)window.location.href=d.url;}\n'
    '    document.getElementById("form").addEventListener("submit",async function(e){\n'
    '      e.preventDefault();\n'
    '      var btn=document.getElementById("btn"),err=document.getElementById("err"),ok=document.getElementById("ok");\n'
    '      var nw=document.getElementById("nw").value,nw2=document.getElementById("nw2").value;\n'
    '      err.style.display="none";ok.style.display="none";\n'
    '      if(nw!==nw2){err.textContent="Passwoerter stimmen nicht ueberein.";err.style.display="block";return;}\n'
    '      btn.disabled=true;btn.textContent="Speichern...";\n'
    '      try{\n'
    '        var r=await api("/api/user/change-password",{method:"POST",headers:{"Content-Type":"application/json"},\n'
    '          body:JSON.stringify({current_password:document.getElementById("cur").value,new_password:nw})});\n'
    '        var d=await r.json();\n'
    '        if(!r.ok)throw new Error(d.detail||"Fehler");\n'
    '        ok.textContent="Passwort geaendert.";ok.style.display="block";document.getElementById("form").reset();\n'
    '      }catch(ex){err.textContent=ex.message;err.style.display="block";}\n'
    '      finally{btn.disabled=false;btn.textContent="Passwort aendern";}\n'
    '    });\n'
    '    load();\n'
    '  </script>\n</body>\n</html>\n',
    encoding="utf-8",
)
print("wrote frontend/account.html")

# ── admin.html ────────────────────────────────────────────────────────────────
(FRONTEND / "admin.html").write_text(
    '<!DOCTYPE html>\n<html lang="de">\n<head>\n'
    '  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
    '  <title>RS Platform - Admin</title>\n'
    '  <style>\n'
    '    *{box-sizing:border-box;margin:0;padding:0}\n'
    '    body{background:#0a0f1e;color:#e2e8f0;font-family:\'Inter\',system-ui,sans-serif;min-height:100vh}\n'
    '    .top{background:#0f172a;border-bottom:1px solid #1e293b;padding:14px 28px;display:flex;align-items:center;gap:20px}\n'
    '    .top h1{font-size:16px;font-weight:600;color:#f1f5f9;flex:1}\n'
    '    .top a{font-size:13px;color:#64748b;text-decoration:none}.top a:hover{color:#94a3b8}\n'
    '    .wrap{max-width:960px;margin:36px auto;padding:0 20px}\n'
    '    .hdr{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}\n'
    '    .hdr h2{font-size:14px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.06em}\n'
    '    .btn{background:#2563eb;border:none;border-radius:6px;color:#fff;font-size:13px;font-weight:500;padding:8px 16px;cursor:pointer}\n'
    '    .btn:hover{background:#1d4ed8}\n'
    '    .btn-sm{padding:4px 10px;font-size:12px;border-radius:4px;border:none;cursor:pointer;font-weight:500}\n'
    '    .btn-danger{background:#450a0a;color:#fca5a5}.btn-danger:hover{background:#7f1d1d}\n'
    '    .btn-muted{background:#1e293b;color:#94a3b8}.btn-muted:hover{background:#334155}\n'
    '    .btn-green{background:#052e16;color:#86efac}.btn-green:hover{background:#166534}\n'
    '    table{width:100%;border-collapse:collapse;font-size:13px}\n'
    '    th{text-align:left;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.06em;padding:8px 10px;border-bottom:1px solid #1e293b}\n'
    '    td{padding:10px;border-bottom:1px solid #0f172a;vertical-align:middle}\n'
    '    tr:hover td{background:#0f172a}\n'
    '    .badge{padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600}\n'
    '    .bp{background:#1e3a5f;color:#60a5fa}.bf{background:#1e293b;color:#94a3b8}\n'
    '    .ba{background:#2d1b00;color:#fbbf24}.bn{background:#1e293b;color:#475569}\n'
    '    .overlay{position:fixed;inset:0;background:rgba(0,0,0,.7);display:none;align-items:center;justify-content:center;z-index:100}\n'
    '    .overlay.on{display:flex}\n'
    '    .modal{background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:32px;width:100%;max-width:400px}\n'
    '    .modal h3{font-size:16px;font-weight:600;margin-bottom:20px;color:#f1f5f9}\n'
    '    .modal label{display:block;font-size:11px;color:#94a3b8;margin-bottom:5px;text-transform:uppercase;letter-spacing:.06em}\n'
    '    .modal input,.modal select{width:100%;background:#1e293b;border:1px solid #334155;border-radius:6px;color:#e2e8f0;font-size:14px;padding:9px 12px;margin-bottom:14px;outline:none}\n'
    '    .modal-row{display:flex;gap:10px;margin-top:8px}.modal-row button{flex:1}\n'
    '    .msg{border-radius:6px;font-size:13px;padding:10px 14px;margin-bottom:14px;display:none}\n'
    '    .err{background:#450a0a;border:1px solid #7f1d1d;color:#fca5a5}\n'
    '    .ok{background:#052e16;border:1px solid #166534;color:#86efac}\n'
    '    .acts{display:flex;gap:6px}\n'
    '  </style>\n</head>\n<body>\n'
    '  <div class="top"><h1>RS Platform - Admin</h1><a href="/account.html">Konto</a><a href="/">Dashboard</a></div>\n'
    '  <div class="wrap">\n'
    '    <div class="msg err" id="gerr"></div><div class="msg ok" id="gok"></div>\n'
    '    <div class="hdr"><h2>Benutzer</h2><button class="btn" onclick="openC()">+ Neuer Benutzer</button></div>\n'
    '    <table><thead><tr><th>E-Mail</th><th>Plan</th><th>Admin</th><th>Status</th><th>Erstellt</th><th>Aktionen</th></tr></thead>\n'
    '    <tbody id="tb"></tbody></table>\n'
    '  </div>\n\n'
    '  <div class="overlay" id="co"><div class="modal">\n'
    '    <h3>Neuer Benutzer</h3><div class="msg err" id="cerr"></div>\n'
    '    <form id="cf">\n'
    '      <label>E-Mail</label><input type="email" id="ce" required placeholder="name@example.com">\n'
    '      <label>Passwort</label><input type="password" id="cp" required placeholder="........">\n'
    '      <label>Plan</label><select id="cpl"><option value="free">Free</option><option value="pro">Pro</option></select>\n'
    '      <label style="display:flex;align-items:center;gap:8px;text-transform:none;margin-bottom:14px">\n'
    '        <input type="checkbox" id="ca" style="width:auto;margin:0"> Admin\n'
    '      </label>\n'
    '      <div class="modal-row"><button type="submit" class="btn">Anlegen</button><button type="button" class="btn btn-muted" onclick="closeC()">Abbrechen</button></div>\n'
    '    </form>\n'
    '  </div></div>\n\n'
    '  <div class="overlay" id="eo"><div class="modal">\n'
    '    <h3 id="et">Benutzer bearbeiten</h3><div class="msg err" id="eerr"></div>\n'
    '    <form id="ef">\n'
    '      <label>Plan</label><select id="epl"><option value="free">Free</option><option value="pro">Pro</option></select>\n'
    '      <label style="display:flex;align-items:center;gap:8px;text-transform:none;margin-bottom:14px">\n'
    '        <input type="checkbox" id="ea" style="width:auto;margin:0"> Admin\n'
    '      </label>\n'
    '      <label>Neues Passwort <span style="color:#475569;text-transform:none">(leer = unveraendert)</span></label>\n'
    '      <input type="password" id="epw" placeholder="........">\n'
    '      <div class="modal-row"><button type="submit" class="btn">Speichern</button><button type="button" class="btn btn-muted" onclick="closeE()">Abbrechen</button></div>\n'
    '    </form>\n'
    '  </div></div>\n\n'
    '  <script>\n'
    '    var _t=localStorage.getItem("rs_token"); if(!_t) window.location.href="/login.html";\n'
    '    var _et=null;\n'
    '    function api(url,o){o=o||{};o.headers=Object.assign({},o.headers,{"Authorization":"Bearer "+_t});return fetch(url,o).then(function(r){if(r.status===401){localStorage.clear();window.location.href="/login.html";}if(r.status===403)window.location.href="/";return r;});}\n'
    '    function flash(id,msg,isErr){var el=document.getElementById(id);el.textContent=msg;el.className="msg "+(isErr?"err":"ok");el.style.display="block";setTimeout(function(){el.style.display="none";},4000);}\n'
    '    async function load(){\n'
    '      var r=await api("/api/admin/users"),users=await r.json(),tb=document.getElementById("tb");\n'
    '      tb.innerHTML="";\n'
    '      users.forEach(function(u){\n'
    '        var pb=u.plan==="pro"?\'<span class="badge bp">Pro</span>\':\'<span class="badge bf">Free</span>\';\n'
    '        var ab=u.is_admin?\'<span class="badge ba">Admin</span>\':\'<span class="badge bn">-</span>\';\n'
    '        var sb=u.is_active?\'<span class="badge bf" style="color:#4ade80">Aktiv</span>\':\'<span class="badge bn">Inaktiv</span>\';\n'
    '        var tb2=u.is_active\n'
    '          ?\'<button class="btn-sm btn-danger" onclick="tog(\\\'\'+u.email+\'\\\',false)">Deaktivieren</button>\'\n'
    '          :\'<button class="btn-sm btn-green"  onclick="tog(\\\'\'+u.email+\'\\\',true)">Aktivieren</button>\';\n'
    '        tb.innerHTML+=\'<tr><td>\'+u.email+\'</td><td>\'+pb+\'</td><td>\'+ab+\'</td><td>\'+sb+\'</td>\'\n'
    '          +\'<td>\'+(u.created_at||"").slice(0,10)+\'</td>\'\n'
    '          +\'<td class="acts"><button class="btn-sm btn-muted" onclick="openE(\\\'\'+u.email+\'\\\',\\\'\'+u.plan+\'\\\',\'+u.is_admin+\')">Bearb.</button>\'+tb2+\'</td></tr>\';\n'
    '      });\n'
    '    }\n'
    '    function openC(){document.getElementById("co").classList.add("on");}\n'
    '    function closeC(){document.getElementById("co").classList.remove("on");document.getElementById("cf").reset();document.getElementById("cerr").style.display="none";}\n'
    '    document.getElementById("cf").addEventListener("submit",async function(e){\n'
    '      e.preventDefault();\n'
    '      var r=await api("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},\n'
    '        body:JSON.stringify({email:document.getElementById("ce").value,password:document.getElementById("cp").value,\n'
    '          plan:document.getElementById("cpl").value,is_admin:document.getElementById("ca").checked})});\n'
    '      var d=await r.json();\n'
    '      if(!r.ok){document.getElementById("cerr").textContent=d.detail;document.getElementById("cerr").style.display="block";return;}\n'
    '      closeC();flash("gok",d.detail,false);load();\n'
    '    });\n'
    '    function openE(email,plan,isAdmin){\n'
    '      _et=email;document.getElementById("et").textContent="Bearbeiten: "+email;\n'
    '      document.getElementById("epl").value=plan;document.getElementById("ea").checked=!!isAdmin;\n'
    '      document.getElementById("epw").value="";document.getElementById("eerr").style.display="none";\n'
    '      document.getElementById("eo").classList.add("on");\n'
    '    }\n'
    '    function closeE(){document.getElementById("eo").classList.remove("on");}\n'
    '    document.getElementById("ef").addEventListener("submit",async function(e){\n'
    '      e.preventDefault();\n'
    '      var body={plan:document.getElementById("epl").value,is_admin:document.getElementById("ea").checked};\n'
    '      var pw=document.getElementById("epw").value; if(pw) body.new_password=pw;\n'
    '      var r=await api("/api/admin/users/"+encodeURIComponent(_et),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});\n'
    '      var d=await r.json();\n'
    '      if(!r.ok){document.getElementById("eerr").textContent=d.detail;document.getElementById("eerr").style.display="block";return;}\n'
    '      closeE();flash("gok","Gespeichert.",false);load();\n'
    '    });\n'
    '    async function tog(email,active){\n'
    '      var r=await api("/api/admin/users/"+encodeURIComponent(email),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:active})});\n'
    '      var d=await r.json();\n'
    '      if(!r.ok){flash("gerr",d.detail,true);return;}\n'
    '      load();\n'
    '    }\n'
    '    load();\n'
    '  </script>\n</body>\n</html>\n',
    encoding="utf-8",
)
print("wrote frontend/admin.html")

# ── login.html: "Passwort vergessen?" link ────────────────────────────────────
lp = FRONTEND / "login.html"
lt = lp.read_text(encoding="utf-8")
if "forgot.html" not in lt:
    lt = lt.replace(
        '<button type="submit" id="btn">Einloggen</button>',
        '<button type="submit" id="btn">Einloggen</button>\n'
        '      <a href="/forgot.html" style="display:block;text-align:center;margin-top:14px;'
        'font-size:13px;color:#64748b;text-decoration:none">Passwort vergessen?</a>'
    )
    lp.write_text(lt, encoding="utf-8")
    print("patched frontend/login.html")

# ── .env.example: SMTP vars ───────────────────────────────────────────────────
ep = ROOT / ".env.example"
et = ep.read_text(encoding="utf-8")
if "SMTP_HOST" not in et:
    ep.write_text(et.rstrip() + "\nSMTP_HOST=smtp.example.com\nSMTP_PORT=587\nSMTP_USER=noreply@example.com\nSMTP_PASS=your-smtp-password\nSMTP_FROM=RS Platform <noreply@example.com>\n", encoding="utf-8")
    print("updated .env.example")

print("\nPhase 4 fertig.")
print("Ersten Admin setzen:")
print("  cd backend && python set_admin.py deine@email.com")
print("Dann Server starten: start.bat")
